# -*- coding: utf-8 -*-

"""
reloadlysdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class RecipientPhone(object):

    """Implementation of the 'RecipientPhone' model.

    TODO: type model description here.

    Attributes:
        country_code (string): TODO: type description here.
        number (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "country_code": 'countryCode',
        "number": 'number'
    }

    def __init__(self,
                 country_code=None,
                 number=None):
        """Constructor for the RecipientPhone class"""

        # Initialize members of the class
        self.country_code = country_code 
        self.number = number 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        country_code = dictionary.get("countryCode") if dictionary.get("countryCode") else None
        number = dictionary.get("number") if dictionary.get("number") else None
        # Return an object of this model
        return cls(country_code,
                   number)
