# -*- coding: utf-8 -*-

"""
reloadlysdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""
from reloadlysdk.models.recipient_phone import RecipientPhone
from reloadlysdk.models.sender_phone import SenderPhone


class ReloadlyAirtimeTopupRequest(object):

    """Implementation of the 'reloadly-airtime-topup-request' model.

    TODO: type model description here.

    Attributes:
        operator_id (string): TODO: type description here.
        amount (string): TODO: type description here.
        use_local_amount (bool): TODO: type description here.
        custom_identifier (string): TODO: type description here.
        recipient_phone (RecipientPhone): TODO: type description here.
        sender_phone (SenderPhone): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "operator_id": 'operatorId',
        "amount": 'amount',
        "use_local_amount": 'useLocalAmount',
        "custom_identifier": 'customIdentifier',
        "recipient_phone": 'recipientPhone',
        "sender_phone": 'senderPhone'
    }

    def __init__(self,
                 operator_id=None,
                 amount=None,
                 use_local_amount=None,
                 custom_identifier=None,
                 recipient_phone=None,
                 sender_phone=None):
        """Constructor for the ReloadlyAirtimeTopupRequest class"""

        # Initialize members of the class
        self.operator_id = operator_id 
        self.amount = amount 
        self.use_local_amount = use_local_amount 
        self.custom_identifier = custom_identifier 
        self.recipient_phone = recipient_phone 
        self.sender_phone = sender_phone 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        operator_id = dictionary.get("operatorId") if dictionary.get("operatorId") else None
        amount = dictionary.get("amount") if dictionary.get("amount") else None
        use_local_amount = dictionary.get("useLocalAmount") if "useLocalAmount" in dictionary.keys() else None
        custom_identifier = dictionary.get("customIdentifier") if dictionary.get("customIdentifier") else None
        recipient_phone = RecipientPhone.from_dictionary(dictionary.get('recipientPhone')) if dictionary.get('recipientPhone') else None
        sender_phone = SenderPhone.from_dictionary(dictionary.get('senderPhone')) if dictionary.get('senderPhone') else None
        # Return an object of this model
        return cls(operator_id,
                   amount,
                   use_local_amount,
                   custom_identifier,
                   recipient_phone,
                   sender_phone)
