# -*- coding: utf-8 -*-

"""
reloadlysdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ReloadlyNumberLookupPostRequest(object):

    """Implementation of the 'reloadly-number-lookup-post-request' model.

    TODO: type model description here.

    Attributes:
        number (string): TODO: type description here.
        country_code (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "number": 'number',
        "country_code": 'countryCode'
    }

    def __init__(self,
                 number=None,
                 country_code=None):
        """Constructor for the ReloadlyNumberLookupPostRequest class"""

        # Initialize members of the class
        self.number = number 
        self.country_code = country_code 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        number = dictionary.get("number") if dictionary.get("number") else None
        country_code = dictionary.get("countryCode") if dictionary.get("countryCode") else None
        # Return an object of this model
        return cls(number,
                   country_code)
