# -*- coding: utf-8 -*-

"""
reloadlysdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""


class ReloadlyAirtimeFxRatesRequest(object):

    """Implementation of the 'reloadly-airtime-fx-rates-request' model.

    TODO: type model description here.

    Attributes:
        operator_id (string): TODO: type description here.
        amount (string): TODO: type description here.

    """

    # Create a mapping from Model property names to API property names
    _names = {
        "operator_id": 'operatorId',
        "amount": 'amount'
    }

    def __init__(self,
                 operator_id=None,
                 amount=None):
        """Constructor for the ReloadlyAirtimeFxRatesRequest class"""

        # Initialize members of the class
        self.operator_id = operator_id 
        self.amount = amount 

    @classmethod
    def from_dictionary(cls,
                        dictionary):
        """Creates an instance of this model from a dictionary

        Args:
            dictionary (dictionary): A dictionary representation of the object
            as obtained from the deserialization of the server's response. The
            keys MUST match property names in the API description.

        Returns:
            object: An instance of this structure class.

        """
        if dictionary is None:
            return None

        # Extract variables from the dictionary

        operator_id = dictionary.get("operatorId") if dictionary.get("operatorId") else None
        amount = dictionary.get("amount") if dictionary.get("amount") else None
        # Return an object of this model
        return cls(operator_id,
                   amount)
