# -*- coding: utf-8 -*-

"""
reloadlysdk

This file was automatically generated by APIMATIC v3.0 (
 https://www.apimatic.io ).
"""

from reloadlysdk.decorators import lazy_property
from reloadlysdk.configuration import Configuration
from reloadlysdk.configuration import Environment
from reloadlysdk.controllers.authentication_controller\
    import AuthenticationController
from reloadlysdk.controllers.airtime_account_balance_controller\
    import AirtimeAccountBalanceController
from reloadlysdk.controllers.airtime_countries_controller\
    import AirtimeCountriesController
from reloadlysdk.controllers.airtime_operators_controller\
    import AirtimeOperatorsController
from reloadlysdk.controllers.airtime_fx_rates_controller\
    import AirtimeFXRatesController
from reloadlysdk.controllers.airtime_commissions_controller\
    import AirtimeCommissionsController
from reloadlysdk.controllers.airtime_promotions_controller\
    import AirtimePromotionsController
from reloadlysdk.controllers.airtime_topups_controller\
    import AirtimeTopupsController
from reloadlysdk.controllers.airtime_transactions_controller\
    import AirtimeTransactionsController
from reloadlysdk.controllers.gift_cards_account_balance_controller\
    import GiftCardsAccountBalanceController
from reloadlysdk.controllers.gift_cards_countries_controller\
    import GiftCardsCountriesController
from reloadlysdk.controllers.gift_cards_products_controller\
    import GiftCardsProductsController
from reloadlysdk.controllers.gift_cards_redeem_instructions_controller\
    import GiftCardsRedeemInstructionsController
from reloadlysdk.controllers.gift_cards_discounts_controller\
    import GiftCardsDiscountsController
from reloadlysdk.controllers.gift_cards_transactions_controller\
    import GiftCardsTransactionsController
from reloadlysdk.controllers.gift_cards_orders_controller\
    import GiftCardsOrdersController
from reloadlysdk.controllers.airtime_number_lookup_controller\
    import AirtimeNumberLookupController
from reloadlysdk.controllers.utility_payments_account_balance_controller\
    import UtilityPaymentsAccountBalanceController
from reloadlysdk.controllers.utility_payments_utility_billers_controller\
    import UtilityPaymentsUtilityBillersController
from reloadlysdk.controllers.utility_payments_pay_bill_controller\
    import UtilityPaymentsPayBillController
from reloadlysdk.controllers.utility_payments_transactions_controller\
    import UtilityPaymentsTransactionsController


class ReloadlysdkClient(object):

    @lazy_property
    def authentication(self):
        return AuthenticationController(self.config)

    @lazy_property
    def airtime_account_balance(self):
        return AirtimeAccountBalanceController(self.config)

    @lazy_property
    def airtime_countries(self):
        return AirtimeCountriesController(self.config)

    @lazy_property
    def airtime_operators(self):
        return AirtimeOperatorsController(self.config)

    @lazy_property
    def airtime_fx_rates(self):
        return AirtimeFXRatesController(self.config)

    @lazy_property
    def airtime_commissions(self):
        return AirtimeCommissionsController(self.config)

    @lazy_property
    def airtime_promotions(self):
        return AirtimePromotionsController(self.config)

    @lazy_property
    def airtime_topups(self):
        return AirtimeTopupsController(self.config)

    @lazy_property
    def airtime_transactions(self):
        return AirtimeTransactionsController(self.config)

    @lazy_property
    def gift_cards_account_balance(self):
        return GiftCardsAccountBalanceController(self.config)

    @lazy_property
    def gift_cards_countries(self):
        return GiftCardsCountriesController(self.config)

    @lazy_property
    def gift_cards_products(self):
        return GiftCardsProductsController(self.config)

    @lazy_property
    def gift_cards_redeem_instructions(self):
        return GiftCardsRedeemInstructionsController(self.config)

    @lazy_property
    def gift_cards_discounts(self):
        return GiftCardsDiscountsController(self.config)

    @lazy_property
    def gift_cards_transactions(self):
        return GiftCardsTransactionsController(self.config)

    @lazy_property
    def gift_cards_orders(self):
        return GiftCardsOrdersController(self.config)

    @lazy_property
    def airtime_number_lookup(self):
        return AirtimeNumberLookupController(self.config)

    @lazy_property
    def utility_payments_account_balance(self):
        return UtilityPaymentsAccountBalanceController(self.config)

    @lazy_property
    def utility_payments_utility_billers(self):
        return UtilityPaymentsUtilityBillersController(self.config)

    @lazy_property
    def utility_payments_pay_bill(self):
        return UtilityPaymentsPayBillController(self.config)

    @lazy_property
    def utility_payments_transactions(self):
        return UtilityPaymentsTransactionsController(self.config)

    def __init__(self, http_client_instance=None,
                 override_http_client_configuration=False, http_call_back=None,
                 timeout=60, max_retries=0, backoff_factor=2,
                 retry_statuses=[408, 413, 429, 500, 502, 503, 504, 521, 522, 524],
                 retry_methods=['GET', 'PUT'],
                 environment=Environment.PRODUCTION, config=None):
        if config is None:
            self.config = Configuration(
                                         http_client_instance=http_client_instance,
                                         override_http_client_configuration=override_http_client_configuration,
                                         http_call_back=http_call_back,
                                         timeout=timeout,
                                         max_retries=max_retries,
                                         backoff_factor=backoff_factor,
                                         retry_statuses=retry_statuses,
                                         retry_methods=retry_methods,
                                         environment=environment)
        else:
            self.config = config


